### ISSUE TITLE
Qless-{Ruby/Python} Style event notifications?

### ISSUE THREAD

**Issue by stephenreay** [pdffiller/qless-php#100]
Part of what makes a Qless-based job/work queue appealing, is that individual workers (either processes or entire nodes) can fail *completely* and it'll keep working.

One area where Qless-PHP doesn't live up to this concept (compared to it's Python and Ruby siblings) is in events/notifications: rather than being using the exiting Qless/Redis pubsub system, the current Event system uses simple PHP callbacks within the job itself, so it's reliant on either the worker process or the parent process to run the callback in the event of a failure. In the event that the failure is because of a network issue, node failure, or e.g. crash of the php runtime, the failure event never fires.

Ideally Qless-PHP would provide an interface to subscribe to the builtin Qless pubsub-based notifications.

This issue is mostly intended to be a discussion item. I'd like to get your thoughts on this (and perhaps you have reasons for having not implemented this already that I haven't considered). If there's no major roadblocks I'll probably work on this soon, as I have a real-world project that would benefit from this functionality.

**Comment by sergeyklay** [comment]
You're absolutely right. However we haven't managed to implement this part yet. And any contributions are always welcome!

**Comment by stephenreay** [comment]
Great to hear, I'll try to make some progress on this soon.

**Comment by stephenreay** [comment]
Thanks to @osadchyi-s for merging in 9dcce89625083586bf514ceda89fbcaefd200dec, I'm gonna close this issue now.

**Comment by sergeyklay** [comment]
I apologize @stephenreay for completely overlooking this. Thank you for the PR and for helping us make Qless better!

**Comment by stephenreay** [comment]
No worries at all, I'm glad I could contribute something back!
