### ISSUE TITLE
Bug on parameters order in 'job' method

### ISSUE THREAD

**Issue by JiSoft** [pdffiller/qless-php#70]
**Description of the bug**
As we know Class Qless\Client uses lua code underhood to deal with workers, queues, jobs and etc.
But the method's description in php code doesn't match lua code exactly
@method string[] jobs(string $state, int $offset = 0, int $count = 25)
For $state = 'complete'  and for other values of state the parameters order in lua function Qless.jobs is not the same. 
So for example, if I run
```php
$client->jobs('stalled', 'my_queue');
```
it works, but PhpStorm marked this line in red color cause it expects 2nd param to be int.
However if I run
```php
$client->jobs('complete', 'my_queue');
```
it produces an exception.
I guess indeed there are no jobs in queue when they are completed, just we need a good decision in code.

**To Reproduce**
1. Call method `jobs` of class `Qless/Client` with state equals 'complete' like following
```php
$client->jobs('complete', 'my_queue');
```
2. You will have got an exception QlessException: Arg "offset" not a number: my_queue
`at LuaScript->run('jobs', array('complete', 'my_queue'))
in Client.php line 159`

**Expected behavior**
Would be nice to have relevant descriptions for method jobs or have method which express the idea `get completed jobs` and `get jobs in queue` or something like this. Also I wish QlessException to be fixed.

Thank, you in advance
![qlessexception](https://user-images.githubusercontent.com/4632714/52112415-20e8bf80-260f-11e9-8a81-ad910ac53d92.png)

**Comment by osadchyi-s** [comment]
https://github.com/pdffiller/qless-php/blob/master/src/qless-core/qless.lua#L76-L82

Look like in Lua method jobs number of parameters depend on the state.
And there is no queue name for the state "complete" in this method. Second parameter (index 1) - offset, third - count.

**Comment by JiSoft** [comment]
https://github.com/pdffiller/qless-php/blob/f88cd00e83b493389185e2c94c75f663728f61dd/src/qless-core/qless.lua#L84
Exactly
However there is an interpretation of arg[1] as queue name. That's I meant.

**Comment by osadchyi-s** [comment]
Ready for dev-master.
