### ISSUE TITLE
Method jobs in lua script can't work for 'waiting' status

### ISSUE THREAD

**Issue by JiSoft** [pdffiller/qless-php#71]
**Description of the bug**
Function Qless.jobs (at lua code) produces an error when we call it with the status 'waiting'.

**To Reproduce**

1. Start several jobs in the same queue like following: make the first job doing a long time to give situation when we have to wait other jobs.

2. Get statistic to be sure we have jobs on 'waiting' status
```php
$client->getCounts();
```
3. Try to get all jobs on status 'waiting'
```php
$client->jobs('waiting', 'my_queue');
```

**Expected behavior**
I wish to get actual jobs on 'waiting' status when they exist or an empty array when they are absent instead of throwing an error.

**Comment by osadchyi-s** [comment]
@JiSoft , you can try changes for dev-master.
