### ISSUE TITLE
Event Handling doesn't work as advertised.

### ISSUE THREAD

**Issue by stephenreay** [pdffiller/qless-php#92]
**Describe the bug**
There are several issues with the way "events" are handled in the current version.

- The "BeforeFork" event is in fact, not fired for workers, "AfterFork" is fired both before and after the fork.
- While `EventsManager::attach` accepts any `callable`, it only actually calls the handler if it's an object (i.e. an instance of `Closure`)

**To Reproduce**
1. Run a Queue with the ForkingWorker
2. Attach a simple callable (i.e. `[$object, 'method']` or a string function name) event handler to to the worker for either the AfterFork or BeforeFork event.

**Expected behavior**
The handler should be called at the appropriate time, either before or after the child process Forks.

**Server (please complete the following information):**
 - OS: Irrelevant
 - Qless version: 3.8.1
 - PHP version: Irrelevant

**Additional context**
I'm writing a PR to fix this now. I'll submit shortly.

**Comment by osadchyi-s** [comment]
Thanks for this fix
#94
